version: '2.7.17'
networks:
  HRSerkan_network:
    driver: bridge
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - HRSerkan_network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: HRSerkan_rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=12345
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - HRSerkan_network