version: '2.7.17'
networks:
  pribas_network:
    driver: bridge
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: serkan
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27018"
    networks:
      - HRSerkan_network
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: java_10_rabbitmq
#    environment:
#      - RABBITMQ_DEFAULT_USER=java10
#      - RABBITMQ_DEFAULT_PASS=123
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
##      - HRSerkan_network